const translations = {
  en: {navMap:'MAP',navDirectory:'DIRECTORY',navQuiz:'QUIZ',navGuide:'GUIDE',navigator:'CAMPUS NAVIGATOR',challenge:'CHALLENGE',exitChallenge:'Exit challenge',heroTitle:'Find your place.',heroTitleAccent:'Follow your way.',heroCopy:'Explore the official ISET Djerba ground-floor plan through a complete interactive campus navigator. Search, select, zoom, pan and follow a route directly on the map.',openMap:'Open campus map ↘',startChallenge:'Start challenge ↗',howItWorks:'How it works',directory:'LOCATION DIRECTORY',findPlace:'Find a place',searchPlaceholder:'Room, lab, department...',all:'All',departments:'Departments',rooms:'Rooms',labs:'Labs',services:'Services',groundPlan:'Ground-floor plan <b>RDC</b>',allPlaces:'All places',academic:'Academic',gesture:'Drag to move · wheel/pinch to zoom · double-tap to zoom',focus:'Focus ↗',interactiveMarkers:'Interactive markers',fullscreen:'⛶ Fullscreen',campusGuide:'CAMPUS GUIDE',guideTitle:'Navigate without getting lost.',searchGuide:'Search',searchGuideCopy:'Search any mapped room, laboratory, department or service.',selectGuide:'Select',selectGuideCopy:'Tap a directory result or a marker directly on the plan.',navigateGuide:'Navigate',navigateGuideCopy:'Focus the destination and display the animated route from the entrance.',helpSearch:'Search or choose a category.',helpSelect:'Select a place from the list or tap a marker.',helpFocus:'Use <b>Focus map</b> to center the destination.',helpRoute:'Use <b>Show route</b> to display the animated path.',helpPhone:'On phone, drag with one finger, pinch with two fingers, or double-tap to zoom.',interactiveLocations:'interactive locations',searchMetric:'SEARCH',live:'LIVE',routeMetric:'ROUTE',animated:'ANIMATED',devicesMetric:'DEVICES',devices:'PC · TABLET · PHONE',sourcePlan:'Source plan · RDC',reset:'Reset',interactiveMap:'INTERACTIVE CAMPUS MAP',officialPlan:'Official plan · 2021—2022',selectPlace:'SELECT A PLACE',campusNavigator:'Campus Navigator',selectLocation:'Select a location from the directory or map.',showRoute:'Show route ↗',focusMap:'Focus map',quickGuide:'QUICK GUIDE',howToUse:'How to use the map',challengeCopy:'Use the official ground-floor plan to locate each room, lab and service. Eight rounds. One map. Your score is live.',findThisPlace:'FIND THIS PLACE',nextPlace:'Next place',challengeReady:'You have eight rounds to build your score.',howToPlay:'HOW TO PLAY',challengeTip:'Tap the matching marker on the plan. A correct answer is worth <b>100 points</b>.',tapMarker:'Tap a marker to answer',openNavigator:'Open navigator ↗',department:'Department',room:'Teaching room',lab:'Laboratory',common:'Campus service',correct:'Correct.',wrong:'Not quite. The correct place is',targetPrompt:'Find the matching marker on the plan.'},
  fr: {navMap:'PLAN',navDirectory:'ANNUAIRE',navQuiz:'QUIZ',navGuide:'GUIDE',navigator:'NAVIGATEUR CAMPUS',challenge:'DÉFI',exitChallenge:'Quitter le défi',heroTitle:'Trouvez votre lieu.',heroTitleAccent:'Suivez votre chemin.',heroCopy:'Explorez le plan officiel du rez-de-chaussée de l’ISET Djerba avec un navigateur interactif complet. Recherchez, sélectionnez et suivez votre itinéraire.',openMap:'Ouvrir le plan ↘',startChallenge:'Commencer le défi ↗',howItWorks:'Comment ça marche',directory:'ANNUAIRE DES LIEUX',findPlace:'Trouver un lieu',searchPlaceholder:'Salle, labo, département...',all:'Tous',departments:'Départements',rooms:'Salles',labs:'Laboratoires',services:'Services',groundPlan:'Plan du rez-de-chaussée <b>RDC</b>',allPlaces:'Tous les lieux',academic:'Académique',gesture:'Glissez pour déplacer · molette/pincement pour zoomer · double-tap pour zoomer',focus:'Centrer ↗',interactiveMarkers:'Marqueurs interactifs',fullscreen:'⛶ Plein écran',campusGuide:'GUIDE DU CAMPUS',guideTitle:'Ne vous perdez plus.',searchGuide:'Rechercher',searchGuideCopy:'Recherchez une salle, un laboratoire, un département ou un service.',selectGuide:'Sélectionner',selectGuideCopy:'Touchez un résultat ou un marqueur sur le plan.',navigateGuide:'Naviguer',navigateGuideCopy:'Centrez la destination et affichez l’itinéraire depuis l’entrée.',interactiveLocations:'lieux interactifs',searchMetric:'RECHERCHE',live:'EN DIRECT',routeMetric:'ITINÉRAIRE',animated:'ANIMÉ',devicesMetric:'APPAREILS',devices:'PC · TABLETTE · TÉLÉPHONE',sourcePlan:'Plan source · RDC',reset:'Réinitialiser',interactiveMap:'PLAN INTERACTIF DU CAMPUS',officialPlan:'Plan officiel · 2021—2022',selectPlace:'SÉLECTIONNEZ UN LIEU',campusNavigator:'Navigateur campus',selectLocation:'Sélectionnez un lieu dans le répertoire ou sur le plan.',showRoute:'Afficher l’itinéraire ↗',focusMap:'Centrer la carte',quickGuide:'GUIDE RAPIDE',howToUse:'Comment utiliser le plan',challengeCopy:'Utilisez le plan officiel pour localiser chaque salle, laboratoire et service. Huit manches. Une carte. Votre score est en direct.',findThisPlace:'TROUVEZ CE LIEU',nextPlace:'Lieu suivant',challengeReady:'Vous avez huit manches pour construire votre score.',howToPlay:'COMMENT JOUER',challengeTip:'Touchez le marqueur correspondant. Une bonne réponse vaut <b>100 points</b>.',tapMarker:'Touchez un marqueur pour répondre',openNavigator:'Ouvrir le navigateur ↗',department:'Département',room:'Salle de cours',lab:'Laboratoire',common:'Service du campus',correct:'Correct.',wrong:'Pas tout à fait. Le bon lieu est',targetPrompt:'Trouvez le marqueur correspondant sur le plan.'},
  ar: {navMap:'الخريطة',navDirectory:'الدليل',navQuiz:'اختبار',navGuide:'الدليل الإرشادي',navigator:'ملاحة الحرم الجامعي',challenge:'التحدي',exitChallenge:'الخروج من التحدي',heroTitle:'اعثر على مكانك.',heroTitleAccent:'واتبع طريقك.',heroCopy:'استكشف المخطط الرسمي للطابق الأرضي في المعهد العالي للدراسات التكنولوجية بجربة. ابحث واختر وتابع طريقك على الخريطة.',openMap:'فتح خريطة الحرم ↘',startChallenge:'ابدأ التحدي ↗',howItWorks:'كيف يعمل؟',directory:'دليل الأماكن',findPlace:'ابحث عن مكان',searchPlaceholder:'قاعة، مخبر، قسم...',all:'الكل',departments:'الأقسام',rooms:'القاعات',labs:'المخابر',services:'الخدمات',groundPlan:'مخطط الطابق الأرضي <b>RDC</b>',allPlaces:'كل الأماكن',academic:'أكاديمي',gesture:'اسحب للتحريك · مرر أو قرّب للتكبير · نقرتان للتكبير',focus:'تركيز ↗',interactiveMarkers:'علامات تفاعلية',fullscreen:'⛶ ملء الشاشة',campusGuide:'دليل الحرم',guideTitle:'تنقّل بدون أن تضل الطريق.',searchGuide:'ابحث',searchGuideCopy:'ابحث عن قاعة أو مخبر أو قسم أو خدمة.',selectGuide:'اختر',selectGuideCopy:'اضغط على نتيجة أو علامة مباشرة على الخريطة.',navigateGuide:'تنقّل',navigateGuideCopy:'ركّز على الوجهة وأظهر المسار من المدخل.',interactiveLocations:'أماكن تفاعلية',searchMetric:'البحث',live:'مباشر',routeMetric:'المسار',animated:'متحرك',devicesMetric:'الأجهزة',devices:'حاسوب · لوحي · هاتف',sourcePlan:'المخطط المصدر · RDC',reset:'إعادة ضبط',interactiveMap:'خريطة الحرم التفاعلية',officialPlan:'المخطط الرسمي · 2021—2022',selectPlace:'اختر مكاناً',campusNavigator:'ملاحة الحرم',selectLocation:'اختر مكاناً من الدليل أو الخريطة.',showRoute:'إظهار المسار ↗',focusMap:'تركيز الخريطة',quickGuide:'دليل سريع',howToUse:'كيفية استعمال الخريطة',challengeCopy:'استعمل المخطط الرسمي لتحديد القاعات والمخابر والخدمات. ثماني جولات. خريطة واحدة. نقاطك مباشرة.',findThisPlace:'اعثر على هذا المكان',nextPlace:'المكان التالي',challengeReady:'لديك ثماني جولات لجمع النقاط.',howToPlay:'طريقة اللعب',challengeTip:'اضغط على العلامة المطابقة في الخريطة. الإجابة الصحيحة تساوي <b>100 نقطة</b>.',tapMarker:'اضغط على علامة للإجابة',openNavigator:'فتح الملاحة ↗',department:'قسم',room:'قاعة تدريس',lab:'مخبر',common:'خدمة جامعية',correct:'إجابة صحيحة.',wrong:'ليست صحيحة. المكان الصحيح هو',targetPrompt:'اعثر على العلامة المطابقة في الخريطة.'}
};

Object.assign(translations.fr, {helpSearch:'Recherchez ou choisissez une catégorie.',helpSelect:'Sélectionnez un lieu dans la liste ou touchez un marqueur.',helpFocus:'Utilisez <b>Centrer la carte</b> pour placer la destination au centre.',helpRoute:'Utilisez <b>Afficher l’itinéraire</b> pour voir le parcours animé.',helpPhone:'Sur téléphone, glissez avec un doigt et utilisez les boutons de zoom.'});
Object.assign(translations.ar, {helpSearch:'ابحث أو اختر فئة.',helpSelect:'اختر مكاناً من القائمة أو اضغط على علامة.',helpFocus:'استعمل <b>تركيز الخريطة</b> لوضع الوجهة في الوسط.',helpRoute:'استعمل <b>إظهار المسار</b> لمشاهدة الطريق المتحرك.',helpPhone:'على الهاتف، اسحب بإصبع واستعمل أزرار التكبير.'});
Object.assign(translations.en, {footerTitle:'Built with curiosity.',footerCopy:'A campus navigator and location challenge created by a first-year ISET Djerba student.',profileLabel:'PROFILE',locationStudent:'Menzel Bourguiba, Bizerte · Tunisia',studyInfo:'1st year · ISET Djerba · IT ',socialLabel:'CONNECT',footerMade:'Made for ISET Djerba',backTop:'Back to top ↑'});
Object.assign(translations.fr, {footerTitle:'Créé avec curiosité.',footerCopy:'Un navigateur du campus et un défi de localisation créé par un étudiant de première année à l’ISET Djerba.',profileLabel:'PROFIL',locationStudent:'Menzel Bourguiba, Bizerte · Tunisie',studyInfo:'1ère année · ISET Djerba · IT ',socialLabel:'CONTACT',footerMade:'Créé pour l’ISET Djerba',backTop:'Retour en haut ↑'});
Object.assign(translations.ar, {footerTitle:'صُنع بشغف وفضول.',footerCopy:'ملاحة للحرم الجامعي وتحدي تحديد المواقع من إعداد طالب سنة أولى في المعهد العالي بجربة.',profileLabel:'الملف الشخصي',locationStudent:'منزل بورقيبة، بنزرت · تونس',studyInfo:'السنة الأولى · ISET جربة · IT ',socialLabel:'تواصل معي',footerMade:'صُنع من أجل ISET جربة',backTop:'العودة إلى الأعلى ↑'});

const savedLanguage = localStorage.getItem('iset-language') || 'en';
const savedTheme = localStorage.getItem('iset-theme') || 'light';
window.siteLanguage = savedLanguage;
window.siteText = translations[savedLanguage];
window.siteTypeLabels = Object.fromEntries(['department','room','lab','common'].map(key => [key, window.siteText[key]]));
window.t = key => window.siteText[key] || key;

function applySiteSettings(language = window.siteLanguage) {
  window.siteLanguage = language;
  window.siteText = translations[language];
  window.siteTypeLabels = Object.fromEntries(['department','room','lab','common'].map(key => [key, window.siteText[key]]));
  document.documentElement.lang = language;
  document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-i18n]').forEach(node => { node.innerHTML = window.siteText[node.dataset.i18n] || node.innerHTML; });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(node => { node.placeholder = window.siteText[node.dataset.i18nPlaceholder] || node.placeholder; });
  const select = document.querySelector('#languageSelect');
  if (select) select.value = language;
  localStorage.setItem('iset-language', language);
  document.dispatchEvent(new CustomEvent('siteLanguageChanged'));
}

function applyTheme(theme) {
  document.documentElement.dataset.theme = theme;
  localStorage.setItem('iset-theme', theme);
  const button = document.querySelector('#themeToggle');
  if (button) { button.textContent = theme === 'dark' ? '☀' : '☾'; button.setAttribute('aria-label', theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'); }
}

document.addEventListener('DOMContentLoaded', () => {
  applySiteSettings(savedLanguage);
  applyTheme(savedTheme);
  document.querySelector('#languageSelect')?.addEventListener('change', event => applySiteSettings(event.target.value));
  document.querySelector('#themeToggle')?.addEventListener('click', () => applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));
});
applyTheme(savedTheme);
